apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-test
  namespace: woodez-database
  labels:
    app: mongodb-testing
  annotations:
        checksum/git-commit: 44a969b5faf6bbf96038b30e4018261945d2f3be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-test
  template:
    metadata:
      labels:
        app: mongodb-test
    spec:
      containers:
      - name: mongodb-test-container
        image: kwood475/python-mongodb-test:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-test-service
  namespace: woodez-database 
  labels:
    app: mongodb-test
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: mongodb-test